channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.3.1
  - bwa=0.7.12
  - graphviz=2.38.0
  - python=3.5.1
  - samtools=1.3.1
  - snakemake=5.4.2
  - pyyaml=3.11
  - admixture=1.3.0
